### ISSUE TITLE
Agregar buscador de imágenes

### ISSUE THREAD

**Issue by Ryusei1** [EduenSarceno/Yumi#5]
Agrégale a esa cosa un buscador de imágenes para que sirva más que rem

**Comment by EduenSarceno** [comment]
veré qué puedo hacer, según vi, kwoth utiliza la api de google, el problema es el rate-limit. Solo para google verdad? o también imgur?

**Comment by Ryusei1** [comment]
solo google, imgur no tiene nada bueno
